server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.96.106.248:3306/nkp
    username: root
    password: Abc123!@#
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.nkp.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

