package com.nkp.dao;

import com.nkp.pojo.NewsType;

public interface NewsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    int insert(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    int insertSelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    NewsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsType
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsType record);
}