package com.nkp.dao;

import com.nkp.pojo.Shrio;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ShrioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    int insert(Shrio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    int insertSelective(Shrio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    Shrio selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shrio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shrio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shrio record);

    @Delete("delete from shrio where uid=#{uid}")
    void deleteNewShrio(int uid);
    @Select("select cid from shrio where uid=#{uid} and tid=#{tid}")
    List<Integer> selShrio(int uid,int tid);
}