package com.nkp.dao;

import com.nkp.pojo.UserInfo;

import java.util.List;


public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    List findAllUser();

    UserInfo check(String userName, String userPW);
}