package com.nkp.dao;

import com.nkp.pojo.ViewNumber;

public interface ViewNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int insert(ViewNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int insertSelective(ViewNumber record);
}